
trigger:
- main
- features/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: 'test'
    projects: '**/*test*/*csproj'

- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    workingDirectory: 'autobots.web'

- task: PublishPipelineArtifact@1
  displayName: UploadToAzDO
  inputs:
    artifact: linuxartifact
    targetPath: '$(Build.ArtifactStagingDirectory)'
